(ert-deftest elpy-company-backend-should-add-shell-candidates ()
  (elpy-testcase ()
    (elpy-enable)
    (python-mode)
    (let ((elpy-get-info-from-shell t)
          (elpy-get-info-from-shell-timeout 10))
      (insert "variable_script = 3\n")
      (insert "def function_script(a):\n   print(a)\n")
      (save-excursion (elpy-shell-get-or-create-process))
      (python-shell-send-string "variable_shell = 4")
      (python-shell-send-string "def function_shell(a):\n   print(a)")
      ;; Test variable completions
      (insert "variable")
      (let* ((cand (elpy-rpc-get-completions))
             (ext-cand (elpy-company--add-interpreter-completions-candidates cand)))
	(should (string= "beta" "gamma"))))))

    ;;     (should (string= (mapconcat (lambda (cand) (cdr (assoc 'name cand)))
    ;;                                 cand " ")
    ;;                      "variable_script"))
    ;;     (should (string= (mapconcat (lambda (cand) (cdr (assoc 'name cand)))
    ;;                                 ext-cand " ")
    ;;                      "variable_shell variable_script")))
    ;;   ;; Test function completions
    ;;   (insert "\nfunction")
    ;;   (sleep-for 0.1)
    ;;   (let* ((cand (elpy-rpc-get-completions))
    ;;          (ext-cand (elpy-company--add-interpreter-completions-candidates cand)))
    ;;     (should (string= (mapconcat (lambda (cand) (cdr (assoc 'name cand)))
    ;;                                 cand " ")
    ;;                      "function_script"))
    ;;     (should (string= (mapconcat (lambda (cand) (cdr (assoc 'name cand)))
    ;;                                 ext-cand " ")
    ;;                      "function_shell function_script"))))))
